[workspace]
members = [
    "crates/server",
    "crates/engine",
    "crates/renderer-core",
    "crates/renderer-skia",
    "crates/player",
]
resolver = "3"

[profile.release]
lto = true
panic = "abort"

[workspace.dependencies]
csscolorparser = "0.7"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
tracing = "0.1"
anyhow = "1.0"
