[package]
name = "player"
version = "0.1.0"
edition = "2024"

[dependencies]
engine = { path = "../engine" }
renderer-skia = { path = "../renderer-skia" }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
zip = "8"
winit = "0.30"
softbuffer = "0.4"
rayon = "1"