[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
csscolorparser = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
renderer-core = { path = "../renderer-core" }
by_address = "1.2.1"
