[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
player = { path = "../player" }
base64 = "0.23"
toml = "1.1"
rayon = "1"
engine = { path = "../engine" }
renderer-skia = { path = "../renderer-skia" }
renderer-pdf = { path = "../renderer-pdf" }
renderer-core = { path = "../renderer-core" }
axum = { version = "0.8.8", features = ["ws"] }
futures-util = "0.3"
clap = { version = "4", features = ["derive"] }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.7", features = ["fs"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rand = "0.10"
notify = "8"
